name: Build Compiler

on:
  workflow_dispatch: # 开启手动触发
    inputs:
      version:
        description: '构建版本'
        required: true
        type: choice
        options:                      
          - gcc-11.5.0
          - gcc-15.2.0

jobs:
  display-params:
    runs-on: ubuntu-latest
    steps:
      - name: 使用手动输入的参数
        run: |
          echo "构建版本: ${{ inputs.version }}"
